/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl;

import org.xtext.example.mydsl.EntityDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class EntityDslStandaloneSetup extends EntityDslStandaloneSetupGenerated {
  public static void doSetup() {
    new EntityDslStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
