/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.entityDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.entityDsl.EntityDslPackage;
import org.xtext.example.mydsl.entityDsl.SimpleType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Simple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SimpleTypeImpl extends TypeImpl implements SimpleType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SimpleTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return EntityDslPackage.Literals.SIMPLE_TYPE;
  }

} //SimpleTypeImpl
