/**
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.entityDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.entityDsl.EntityDslPackage#getSimpleType()
 * @model
 * @generated
 */
public interface SimpleType extends Type
{
} // SimpleType
