/*
 * generated by Xtext 2.12.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.example.entitydsl.ui.internal.EntitydslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class EntityDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return EntitydslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return EntitydslActivator.getInstance().getInjector(EntitydslActivator.ORG_XTEXT_EXAMPLE_MYDSL_ENTITYDSL);
	}
	
}
